#!/usr/bin/env bash
# embed-lua.sh — (re)generate gcalsrv_lua.h from gcalsrv.lua.
#
# The EXE carries the default request-logic script embedded as a byte array, so it's
# self-contained. At startup it prefers an external <exedir>\gcalsrv.lua (customise
# freely), falling back to this embedded copy.
set -euo pipefail
if ! command -v python3 >/dev/null 2>&1; then
  exec nix shell nixpkgs#python3 --command bash "$0" "$@"
fi
here="$(cd "$(dirname "$0")" && pwd)"

python3 - "$here/gcalsrv.lua" > "$here/gcalsrv_lua.h" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
out = ["/* gcalsrv_lua.h - GENERATED by embed-lua.sh from gcalsrv.lua. Do not edit. */",
       "#ifndef GCALSRV_LUA_H", "#define GCALSRV_LUA_H",
       "static const unsigned char GCALSRV_LUA[] = {"]
for i in range(0, len(data), 12):
    out.append("  " + "".join("0x%02x, " % b for b in data[i:i+12]).rstrip())
out.append("};")
out.append("static const unsigned int GCALSRV_LUA_LEN = %d;" % len(data))
out.append("#endif /* GCALSRV_LUA_H */")
print("\n".join(out))
PY
echo "--- wrote $here/gcalsrv_lua.h from gcalsrv.lua ($(wc -c < "$here/gcalsrv.lua") bytes) ---"
