#!/usr/bin/env bash
# embed-pfx.sh — (re)generate cert_pfx.h from the shared self-signed fixture.
#
# The native server is one self-contained EXE: it carries the www.google.com
# cert+key as an embedded PKCS#12 blob (no external key file on the XP box).
# At startup it (a) PFXImportCertStore()s this blob to get Schannel's server
# credential and (b) installs the public cert into XP's Root so WinINet trusts
# the TLS ClientLogin endpoint.
#
# The PFX MUST use the legacy XP-era PKCS#12 PBE (pbeWithSHA1And3-KeyTripleDES-CBC
# + SHA-1 MAC) — XP SP3's PFXImportCertStore cannot parse OpenSSL 3.x's default
# PBES2/AES-256/SHA-256. We regenerate it here from the committed crt+key so the
# served cert == the cert installed in Root (same thumbprint), byte-for-byte.
set -euo pipefail
# Bring openssl + python3 onto PATH from nix if they aren't already (minimal host).
if ! command -v openssl >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
  exec nix shell nixpkgs#openssl nixpkgs#python3 --command bash "$0" "$@"
fi
here="$(cd "$(dirname "$0")" && pwd)"
certs="$here/../gcal-emu/certs"     # single source of truth for the cert identity
pass="gcalc"

openssl pkcs12 -export -legacy \
  -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -macalg sha1 \
  -inkey "$certs/xp-google.key" -in "$certs/xp-google.crt" \
  -name "www.google.com" -passout "pass:$pass" \
  -out "$certs/xp-google.pfx"

# Emit the C header (portable; no xxd dependency).
python3 - "$certs/xp-google.pfx" "$pass" > "$here/cert_pfx.h" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
pwd  = sys.argv[2]
out  = []
out.append("/* cert_pfx.h - GENERATED by embed-pfx.sh. Do not edit by hand.")
out.append(" * Self-signed www.google.com fixture (RSA-2048/SHA-1), XP-legacy PKCS#12.")
out.append(" * Source: tools/gcal-emu/certs/xp-google.{crt,key}; identity is NOT a secret")
out.append(" * (a fake-Google fixture for a LAN-isolated retro box). %d bytes. */" % len(data))
out.append("#ifndef CERT_PFX_H")
out.append("#define CERT_PFX_H")
out.append("static const unsigned char CERT_PFX[] = {")
for i in range(0, len(data), 12):
    chunk = data[i:i+12]
    out.append("  " + "".join("0x%02x, " % b for b in chunk).rstrip())
out.append("};")
out.append("static const unsigned int CERT_PFX_LEN = %d;" % len(data))
out.append('static const wchar_t CERT_PFX_PASS[] = L"%s";' % pwd)
out.append("#endif /* CERT_PFX_H */")
print("\n".join(out))
PY
echo "--- wrote $here/cert_pfx.h ($(wc -l < "$here/cert_pfx.h") lines) from $certs/xp-google.pfx ---"
