[NAME]
Name=Akira Kogami

[POS]
Center=115
BustX=79
BustY=216
BustW=74
BustH=51
SerifX=-152
SerifY=127

[Msg]
;Line: new version available
SerifNewVersion=Oooh~!\nA brand new version\nseems to be out~

;Line: mail received
SerifMailCheck=Mornin, lucky~\nLooks like you got mail\nAs expected of a popular girl

;Line: mail server login failed
SerifMailError=Tch...\nCan you not even set up\nyour own mail?\nYou really are useless

;Line: no new mail
SerifMailNone=Nooo~\nNo mail at all?\nAkira is gonna cry~

;Line: no schedule today
SerifCallenderNone=Oh my\nNothing scheduled today~\nBye-nee~

;Line: calendar - has schedule
SerifCallenderSchedule=Kyaan~ Today, your plans are\n<%SCHEDULE%>\nright?\nLet us give it our all~

;Line: calendar - login failed
SerifCallenderError=Come on already...\nwhy did the calendar setup\nfail this time?

;Line: calendar - no ID registered
SerifCallenderNoAccount=Listen, to use the calendar you need a Google Calendar ID, okay?\nAkira doesn't get it~

