[NAME]
Name=Ami & Mami Futami

[POS]
Center=178
BustX=102
BustY=170
BustW=178
BustH=47
SerifX=-151
SerifY=70

[Msg]
;Line: new version available
SerifNewVersion=Ami Ami!\nA new version is out~\nMami Mami!\nWe gotta check it, right~

;Line: mail received
SerifMailCheck=Bro, you got mail!

;Line: mail server login failed
SerifMailError=Uwaaah\nwe couldn't go grab the mail!

;Line: no new mail
SerifMailNone=Nothing came in→!\nBro's so laaame→♪

;Line: no schedule today
SerifCallenderNone=There's nothing today~\nBro, if you're bored\nlet's play some Xbox→!

セリフ：カレンダー：予定アリ
SerifCallenderSchedule=Bro's schedule today is\n<%SCHEDULE%>\nhuh\nLet's smash it to pieces!

;Line: calendar - login failed
SerifCallenderError=Bro, bro, what do we do!\nWe can't get into the calendar

;Line: calendar - no ID registered
SerifCallenderNoAccount=Hey bro\nto use the calendar you need a Google Calendar ID

