[NAME]
Name=Ayano Minegishi

[POS]
Center=69
BustX=16
BustY=173
BustW=82
BustH=56
SerifX=-175
SerifY=84


[Msg]
;Line: new version available
SerifNewVersion=Looks like a new version\nhas been released

;Line: mail received
SerifMailCheck=Oh\nseems you have some mail?

;Line: mail server login failed
SerifMailError=I couldn't read the mail\nmaybe the settings\nare wrong

;Line: no new mail
SerifMailNone=Looks like there's no mail\nNow now\ndon't be so cross

;Line: no schedule today
SerifCallenderNone=I see, no plans today...\nShall we take it easy then?

;Line: calendar - has schedule
SerifCallenderSchedule=Today's schedule is\n<%SCHEDULE%>\nright?\nDo your best out there

;Line: calendar - login failed
SerifCallenderError=Looks like I couldn't get\ninto the calendar\nDid something go wrong?

;Line: calendar - no ID registered
SerifCallenderNoAccount=To use the calendar you need a Google Calendar ID, it seems

