[NAME]
Name=Azusa Miura

[POS]
Center=85
BustX=25
BustY=180
BustW=131
BustH=72
SerifX=-149
SerifY=77


[Msg]
;Line: new version available
SerifNewVersion=Oh my~\nthe version went up\nI wonder if there's a feature\nto meet my destined one~

;Line: mail received
SerifMailCheck=Producer\nyou seem to have some mail~

;Line: mail server login failed
SerifMailError=Oh my~\nlooks like the mail settings\naren't quite right~

;Line: no new mail
SerifMailNone=Oh dear~\ndid I drop the letter\nsomewhere along the way~?

;Line: no schedule today
SerifCallenderNone=Oh my~\nif there are no outings planned\nthen I won't get lost, will I~

;Line: calendar - has schedule
SerifCallenderSchedule=Um, today you have\n<%SCHEDULE%>\nI see

;Line: calendar - login failed
SerifCallenderError=Oh my~\nI couldn't get into the calendar\nwhatever shall we do~

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer\nto use the calendar you need a Google Calendar ID

