[NAME]
Name=Chihaya Kisaragi

[POS]
Center=91
BustX=45
BustY=176
BustW=111
BustH=47
SerifX=-154
SerifY=62

[Msg]
;Line: new version available
SerifNewVersion=A new version appears\nto be available\nLet's install it to improve\nour lesson efficiency

;Line: mail received
SerifMailCheck=Producer\nyou have mail

;Line: mail server login failed
SerifMailError=Pull yourself together\nyour mail isn't set up

;Line: no new mail
SerifMailNone=No requests...\nUgh...\nthe humiliation...!

;Line: no schedule today
SerifCallenderNone=No plans, I see...\nWith this much free time\nwe could practice all year

;Line: calendar - has schedule
SerifCallenderSchedule=Producer\ntoday's schedule is\n<%SCHEDULE%>\nLet's do our best

;Line: calendar - login failed
SerifCallenderError=Ugh...\nI can't get into the calendar\nUnbelievable...

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer\nto use the calendar you need a Google Calendar ID

