[NAME]
Name=Haruka Amami

[POS]
Center=83
BustX=49
BustY=167
BustW=113
BustH=57
SerifX=-135
SerifY=93

[Msg]
;Line: new version available
SerifNewVersion=Ah\nit's a new version!\nLet's install it right away!

;Line: mail received
SerifMailCheck=Producer\nmail! It's mail!

;Line: mail server login failed
SerifMailError=Produuucer~\nI couldn't receive the mail

;Line: no new mail
SerifMailNone=No mail...\nwhoaa\nso you have no friends~

;Line: no schedule today
SerifCallenderNone=No work again today...\nI'm supposed to be the heroine, right?

;Line: calendar - has schedule
SerifCallenderSchedule=Producer\ntoday it's\n<%SCHEDULE%>\nright?\nLet's get fired up!

;Line: calendar - login failed
SerifCallenderError=P-Producer!\nI can't get into the calendar!!

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer\nto use the calendar you need a Google Calendar ID, it seems

