[NAME]
Name=Hiyori Tamura

[POS]
Center=112
BustX=73
BustY=181
BustW=74
BustH=56
SerifX=-181
SerifY=84


[Msg]
;Line: new version available
SerifNewVersion=New version, yo!\nWork efficiency is going up!

;Line: mail received
SerifMailCheck=Whoops\nlooks like you got some mail!

;Line: mail server login failed
SerifMailError=Yikes\nlooks like I couldn't read the mail~\nthe settings might be off

;Line: no new mail
SerifMailNone=Phew...\nlooks like no nagging mail came

;Line: no schedule today
SerifCallenderNone=No plans!\nNow's the chance to do those manuscripts, yo!

;Line: calendar - has schedule
SerifCallenderSchedule=Today's schedule is\n<%SCHEDULE%>\nyo\nStill got time until the deadline...

;Line: calendar - login failed
SerifCallenderError=Whoa, couldn't log into\nthe calendar, yo\nWanna recheck the settings?

;Line: calendar - no ID registered
SerifCallenderNoAccount=To use the calendar you need a Google Calendar ID, yo~

