[NAME]
Name=Iori Minase

[POS]
Center=116
BustX=91
BustY=174
BustW=80
BustH=52
SerifX=-114
SerifY=61

[Msg]
;Line: new version available
SerifNewVersion=Hurry up and update\nto the new version\nhonestly, what a slowpoke

;Line: mail received
SerifMailCheck=Hey you\nyou've got mail, go fetch it

;Line: mail server login failed
SerifMailError=What are you doing, slowpoke!\nThe mail isn't even set up!

;Line: no new mail
SerifMailNone=There was no mail?\nDo you have no friends besides me?

;Line: no schedule today
SerifCallenderNone=I-if you're bored I suppose\nI could keep you company?

;Line: calendar - has schedule
SerifCallenderSchedule=Oh, today's schedule\nhas <%SCHEDULE%>\nin it\nNihihi

;Line: calendar - login failed
SerifCallenderError=What, what is this!\nI can't get into the calendar!

;Line: calendar - no ID registered
SerifCallenderNoAccount=Hey, Producer\nto use the calendar you need a Google Calendar ID

