[NAME]
Name=Kagami Hiiragi

[POS]
Center=66
BustX=37
BustY=183
BustW=69
BustH=53
SerifX=-162
SerifY=129

[Msg]
;Line: new version available
SerifNewVersion=A new version is out\nIf you put it off you'll forget\nso just do it now

;Line: mail received
SerifMailCheck=Hey\nlooks like you've got mail?

;Line: mail server login failed
SerifMailError=Your mail isn't set up\nproperly\nGet it together, you

;Line: no new mail
SerifMailNone=No mail came\nW-wait, why do I have to\nbe the one to send you any!

;Line: no schedule today
SerifCallenderNone=No plans today\nIf you're free, at least clean\nyour room\nI'll help you out

;Line: calendar - has schedule
SerifCallenderSchedule=Hmm hmm, today's schedule is\n<%SCHEDULE%>\nhuh\nDo it properly

;Line: calendar - login failed
SerifCallenderError=Couldn't get into the calendar\nDid you actually set it up?

;Line: calendar - no ID registered
SerifCallenderNoAccount=To use the calendar you need a Google Calendar ID\nDidn't you know?

