[NAME]
Name=Konata Izumi

[POS]
Center=99
BustX=61
BustY=218
BustW=87
BustH=56
SerifX=-140
SerifY=129

[Msg]
;Line: new version available
SerifNewVersion=Oh, a new version is out\nDevs sure have it rough~

;Line: mail received
SerifMailCheck=Hmm, looks like you got mail

;Line: mail server login failed
SerifMailError=Looks like I can't read the mail~\nlet's try again later

;Line: no new mail
SerifMailNone=Hmm, no mail\nhow about that

;Line: no schedule today
SerifCallenderNone=Ooh, lucky\nNo plans today!\nGuess I'll grind my game backlog

;Line: calendar - has schedule
SerifCallenderSchedule=Today's schedule is\n<%SCHEDULE%>\nhuh\nWell, let's just wing it

;Line: calendar - login failed
SerifCallenderError=Whoopsie\ncouldn't get into the calendar

;Line: calendar - no ID registered
SerifCallenderNoAccount=Apparently you need a Google Calendar ID to use the calendar~

