[NAME]
Name=Kotori Otonashi

[POS]
Center=83
BustX=41
BustY=165
BustW=112
BustH=68
SerifX=-153
SerifY=62

[Msg]
;Line: new version available
SerifNewVersion=A new version appears\nto be available\nPlease check it right away

;Line: mail received
SerifMailCheck=Producer\nyou have mail

;Line: mail server login failed
SerifMailError=Oh dear\nlooks like the mail isn't\nset up properly

;Line: no new mail
SerifMailNone=No mail from anyone...\nhow worrying...\nd-don't tell me it's all\ncaught in the spam filter!?

;Line: no schedule today
SerifCallenderNone=Aaah...\nno job requests today either...\nthe biggest crisis since 765 Pro began!

;Line: calendar - has schedule
SerifCallenderSchedule=Producer\ntoday's schedule has\n<%SCHEDULE%>\nin it

;Line: calendar - login failed
SerifCallenderError=I couldn't get into the calendar\nPlease check the settings

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer,\nto use the calendar you need a Google Calendar ID

