[NAME]
Name=Makoto Kikuchi

[POS]
Center=98
BustX=70
BustY=206
BustW=99
BustH=51
SerifX=-120
SerifY=86

[Msg]
;Line: new version available
SerifNewVersion=Alright! New version is out!\nSomehow it's exciting, huh!

;Line: mail received
SerifMailCheck=Producer\nyou've got mail!

;Line: mail server login failed
SerifMailError=Agh!\nI couldn't read the mail!\nWhat do I do...

;Line: no new mail
SerifMailNone=Um, there was nothing...\nOh!\nit's a letter only fools can't see, right!

;Line: no schedule today
SerifCallenderNone=No plans, huh\nOh!\nif you're free wanna do some Billy's Bootcamp!?

;Line: calendar - has schedule
SerifCallenderSchedule=Producer\ntoday it's\n<%SCHEDULE%>\nright!\nLet's go full throttle!

;Line: calendar - login failed
SerifCallenderError=Producer!\nI can't get into the calendar\nWhat do we do?

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer\napparently you need a Google Calendar ID to use the calendar

