[NAME]
Name=Miki Hoshii

[POS]
Center=92
BustX=50
BustY=185
BustW=124
BustH=69
SerifX=-140
SerifY=93

[Msg]
;Line: new version available
SerifNewVersion=Afuu...\na new version is out\nbut checking it is such a pain

;Line: mail received
SerifMailCheck=Afuu...\nyou've got mail

;Line: mail server login failed
SerifMailError=What do we do, Honey\nI can't read the mail

;Line: no new mail
SerifMailNone=Afuu...\ngetting no mail is so sad,\nHoney...\nMiki will mail youÅÙ

;Line: no schedule today
SerifCallenderNone=Munya... free again today...\nmentaiko rice balls are\nthe best in the world... y'know...

;Line: calendar - has schedule
SerifCallenderSchedule=Honey's schedule is\n<%SCHEDULE%>\ny'know\ndo your best, 'kay

;Line: calendar - login failed
SerifCallenderError=I can't get into the calendar~\nafuu...

;Line: calendar - no ID registered
SerifCallenderNoAccount=Hey Honey\nto use the calendar you need a Google Calendar ID

