[NAME]
Name=Minami Iwasaki

[POS]
Center=73
BustX=39
BustY=192
BustW=69
BustH=52
SerifX=-167
SerifY=96

[Msg]
;Line: new version available
SerifNewVersion=A new version is out...\num... shall we go check it?

;Line: mail received
SerifMailCheck=Um...\nlooks like you have mail

;Line: mail server login failed
SerifMailError=I couldn't read the mail...\nyou should check the mail\nsettings, I think...

;Line: no new mail
SerifMailNone=Mail...\ndoesn't seem to have come

;Line: no schedule today
SerifCallenderNone=No plans today, huh...

;Line: calendar - has schedule
SerifCallenderSchedule=Today's schedule is...\n<%SCHEDULE%>\nright\nAre you okay...?

;Line: calendar - login failed
SerifCallenderError=I couldn't get into the calendar...\nShall we check the settings?

;Line: calendar - no ID registered
SerifCallenderNoAccount=To use the calendar you need a Google Calendar ID, it seems...

