[NAME]
Name=Misao Kusakabe

[POS]
Center=101
BustX=57
BustY=190
BustW=88
BustH=51
SerifX=-161
SerifY=84

[Msg]
;Line: new version available
SerifNewVersion=Ta-daa!\nNew version is out!\nWooooo!!

;Line: mail received
SerifMailCheck=Ooh\nyou've got mail-- gwah!

;Line: mail server login failed
SerifMailError=Aah\ncouldn't read the mail\nwell, no biggie, no biggie

;Line: no new mail
SerifMailNone=Ha-ha\nno mail, huh\nguess you're hated?

;Line: no schedule today
SerifCallenderNone=Aw man, no plans?\nSomebody play with me--

;Line: calendar - has schedule
SerifCallenderSchedule=Today there's\n<%SCHEDULE%>\nhuh\nwell, do your best

;Line: calendar - login failed
SerifCallenderError=Huh? What's this?\nCouldn't get into the calendar?

;Line: calendar - no ID registered
SerifCallenderNoAccount=Apparently you need a Google Calendar ID to use the calendar

