[NAME]
Name=Miyuki Takara

[POS]
Center=129
BustX=86
BustY=199
BustW=97
BustH=62
SerifX=-122
SerifY=116

[Msg]
;Line: new version available
SerifNewVersion=Oh, a new version has\nbeen released, it seems\nFufu

;Line: mail received
SerifMailCheck=Oh my\nlooks like you've got mail

;Line: mail server login failed
SerifMailError=Oh dear\nthe mail settings seem\nto be wrong

;Line: no new mail
SerifMailNone=My apologies\nit seems no mail has arrived

;Line: no schedule today
SerifCallenderNone=There don't seem to be any plans\nUfufu\nShall we relax today?

;Line: calendar - has schedule
SerifCallenderSchedule=Today's schedule seems\nto have <%SCHEDULE%>\nin it\nGood luck

;Line: calendar - login failed
SerifCallenderError=I can't get into the calendar\nI wonder if the settings are wrong?

;Line: calendar - no ID registered
SerifCallenderNoAccount=Did you get a Google Calendar ID?\nYou need one to use the calendar

