[NAME]
Name=Patricia Martin

[POS]
Center=86
BustX=52
BustY=205
BustW=80
BustH=60
SerifX=-154
SerifY=115

[Msg]
;Line: new version available
SerifNewVersion=New version is out-NE!\nCome on, come on\ncheck it right away-YO!

;Line: mail received
SerifMailCheck=OH!\nlooks like you've got mail-NE

;Line: mail server login failed
SerifMailError=Aw, can't read the mail-NE\nMaybe the mail settings are wrong-NE

;Line: no new mail
SerifMailNone=OH!\nthe spam filter here is strong-NE?

;Line: no schedule today
SerifCallenderNone=No plans, how lucky-NE\nI'll read manga all day-YO

;Line: calendar - has schedule
SerifCallenderSchedule=FUM... today's schedule is\n<%SCHEDULE%>\n-NE\nGood luck-NE

;Line: calendar - login failed
SerifCallenderError=OH! Can't get into the calendar-YO\nmaybe the settings are wrong-KA?

;Line: calendar - no ID registered
SerifCallenderNoAccount=To use the calendar you need a Google Calendar ID-YO

