[NAME]
Name=Ritsuko Akizuki

[POS]
Center=93
BustX=66
BustY=182
BustW=123
BustH=74
SerifX=-113
SerifY=74

[Msg]
;Line: new version available
SerifNewVersion=A new version is out, it seems\nChecking out new things\nis also a producer's job

;Line: mail received
SerifMailCheck=Producer\nyou have mail

;Line: mail server login failed
SerifMailError=Producer!\nyou can't even set up\nyour own mail?

;Line: no new mail
SerifMailNone=Not even spam comes in\njust how much of a NEET\nare you, Producer?

;Line: no schedule today
SerifCallenderNone=No work again today\nAre you trying to bankrupt the office?

;Line: calendar - has schedule
SerifCallenderSchedule=Producer\ntoday's schedule is\n<%SCHEDULE%>\nright?\nLet's do this properly

;Line: calendar - login failed
SerifCallenderError=I couldn't get into the calendar\nDid you set it up properly?

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer\nto use the calendar you need a Google Calendar ID

