[NAME]
Name=Tsukasa Hiiragi

[POS]
Center=94
BustX=60
BustY=218
BustW=70
BustH=56
SerifX=-160
SerifY=129

[Msg]
;Line: new version available
SerifNewVersion=Fuwa\na new one's out, huh

;Line: mail received
SerifMailCheck=Ah, looks like you've got mail

;Line: mail server login failed
SerifMailError=Myuu\nI couldn't read the mail

;Line: no new mail
SerifMailNone=No way...

;Line: no schedule today
SerifCallenderNone=Waa\nwe can relax today

;Line: calendar - has schedule
SerifCallenderSchedule=Um, um, today's schedule is\n<%SCHEDULE%>\nright\nlet's do our best

;Line: calendar - login failed
SerifCallenderError=Auu\nI can't get into the calendar~

;Line: calendar - no ID registered
SerifCallenderNoAccount=U-um\nto use the calendar you need\na Google Calendar ID, it seems

