[NAME]
Name=Yayoi Takatsuki

[POS]
Center=103
BustX=59
BustY=187
BustW=90
BustH=47
SerifX=-160
SerifY=83

[Msg]
;Line: new version available
SerifNewVersion=A new one's out!\nmaybe this'll make things\nmore and more convenient

;Line: mail received
SerifMailCheck=Uh-uh!\nyou've got mail!

;Line: mail server login failed
SerifMailError=Producer\nwhat do we do...\nI couldn't read the mail

;Line: no new mail
SerifMailNone=Uh-uh!\ndata charges cost money too\nso having no mail is better!

;Line: no schedule today
SerifCallenderNone=Uh-uh!\nif you're free, come to the\nsupermarket sale with me!

;Line: calendar - has schedule
SerifCallenderSchedule=Uh-uh!\ntoday's schedule is\n<%SCHEDULE%>\nGet pumped, high-touch!

;Line: calendar - login failed
SerifCallenderError=Uuh...\nmaybe I can't get into the calendar...

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer\nyou might need a Google Calendar ID for the calendar

