[NAME]
Name=Yukiho Hagiwara

[POS]
Center=69
BustX=21
BustY=180
BustW=110
BustH=52
SerifX=-195
SerifY=50

[Msg]
;Line: new version available
SerifNewVersion=Ah, a new version was announced\n...it seems\na-am I an unwanted old girl now?

;Line: mail received
SerifMailCheck=Producer\nlooks like you've got mail

;Line: mail server login failed
SerifMailError=Hauu, I'm sorry\nthe mail settings seem\nto be wrong\nhauu~

;Line: no new mail
SerifMailNone=U-um\nthere are no letters to fill in~...

;Line: no schedule today
SerifCallenderNone=Um, if there's nothing to do\nmay I go dig a hole\nover there...

;Line: calendar - has schedule
SerifCallenderSchedule=Um, uh, today's schedule is\n<%SCHEDULE%>\nright\nu-um, let's do our best...

;Line: calendar - login failed
SerifCallenderError=I couldn't get into the calendar...\nI'll go bury myself in a hole

;Line: calendar - no ID registered
SerifCallenderNoAccount=Producer,\nto use the calendar you need a Google Calendar ID, it seems.

